service: vf-project

plugins:
  - index

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "DataBucket" }, "/*" ] ]  }
    - Effect: "Allow"
      Action:
        - "dynamodb:BatchWriteItem"
      Resource: { "Fn::Join" : ["", ["arn:aws:dynamodb:us-east-1:*:table/", { "Ref" : "DataTable" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"

functions:
  processData:
    handler: handler.process

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: vf-sls-data
    DataTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: episodes
          AttributeDefinitions:
            -
              AttributeName: "EpisodeId"
              AttributeType: "S"
            -
              AttributeName: "EpisodeTitle"
              AttributeType: "S"
          KeySchema:
            -
              AttributeName: "EpisodeId"
              KeyType: "HASH"
            -
              AttributeName: "EpisodeTitle"
              KeyType: "RANGE"
          BillingMode: PROVISIONED
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  Outputs:
     NewOutput:
       Description: "Description for the output"
       Value: ""
